### ISSUE TITLE
Die on Apollo Lake

### ISSUE THREAD

**Issue by Peter9606** [intel/ros2_intel_movidius_ncs#10]

**Comment by Peter9606** [comment]
Thanks @congliu0913 for greate help.

**Comment by Peter9606** [comment]
@chaoli2  one thing should be awared is that this issue doesn't only happen on Apollo, it could happen anywhere as long as the cpu doesn't support the flag.

**Comment by Peter9606** [comment]
@testkit PR #11 is already there same as ros.

**Comment by chaoli2** [comment]
PR merged. Thanks.
