### ISSUE TITLE
when I compile NCS graph in ros2 environment,I got an error:

### ISSUE THREAD

**Issue by RachelRen05** [intel/ros2_intel_movidius_ncs#12]
```
cd /opt/movidius/ncappzoo/caffe/AlexNet
make
```
Error brief description:
`Error in `python3': free(): invalid pointer/Error in `python3': double free or corruption`

**Comment by xhuan28** [comment]
It is potentially an issue of NCAPPZOO(upstream issue). We will not fix it.

**Comment by RachelRen05** [comment]
We found a solution here:
https://github.com/pytorch/pytorch/issues/2314
Note:There are many opinions that this problem  is caused by installing python via pip.
