### ISSUE TITLE
Can not run CNN Demo-MobileNet_SSD

### ISSUE THREAD

**Issue by RachelRen05** [intel/ros2_intel_movidius_ncs#3]
When I run:
**ros2 run movidius_ncs_example movidius_ncs_example_image_detection /opt/movidius/ncappzoo/data/images/cat.jpg**
There was an error:
/home/renzhen/ros2_ws/install/lib/movidius_ncs_example/movidius_ncs_example_image_detection: error while loading shared libraries: **libopencv_highgui3.so.3.3**: cannot open shared object file: No such file or directory
tips:I have installed opencv separately.

**Comment by RachelRen05** [comment]
The environment where both ros and ros2 exist is OK now.Maybe this problem is caused by my installation error.

**Comment by chaoli2** [comment]
Close this thread since issue is resolved. Feel free to re-open this issue when need further assist.
