### ISSUE TITLE
Which ROS2 version?

### ISSUE THREAD

**Issue by farbod1277** [intel/ros2_intel_movidius_ncs#51]
Will this work on all ROS2 releases or only ROS2 Ardent? Thank you

**Comment by chaoli2** [comment]
@farbod1277 
This project works only on ROS2 Ardent.
Movidius NCS support has already been migrated to [ros2_openvino_toolkit](https://github.com/intel/ros2_openvino_toolkit), which keeps same pace with ROS2 latest distribution.

**Comment by farbod1277** [comment]
Thank you
