### ISSUE TITLE
About the problem of not finding the libopencv_highgui3.so.3.3 library

### ISSUE THREAD

**Issue by RachelRen05** [intel/ros2_intel_movidius_ncs#6]
The test results are as follows:
`1`Only install ROS2,Test is OK
`2`ROS and ROS2 are both present,There is an error when running video Demo
error log:**error while loading shared libraries: libopencv_highgui3.so.3.3: cannot open shared object file: No such file or directory**
`3`Finding **libopencv_highgui3.so.3.3** library in ROS

**Comment by RachelRen05** [comment]
The environment where both ros and ros2 exist is OK now.Maybe this problem is caused by my installation error.

**Comment by chaoli2** [comment]
Close this thread since issue is resolved. Feel free to re-open this issue when need further assist.
